const columnLabels = {
  id: "ID",
  username: "Tên Đăng Nhập",
  password: "Mật Khẩu",
  email: "Email",
  isActive: "Kích Hoạt",
  createdAt: "Ngày Tạo",
  updatedAt: "Ngày Cập Nhật",
  role: "Vai Trò",
  fullName: "Họ Và Tên",
  phone: "Số Điện Thoại",
  address: "Địa Chỉ",
  avatarUrl: "Ảnh đại diện",
  name: "Tên",
  slug: "Slug",
  logoUrl: "Logo",
  description: "Mô Tả",
  website: "Website",
  imageUrl: "Ảnh",
  title: "Tiêu Đề",
  productName: "Tên Sản Phẩm",
  category: "Danh Mục",
  manufacturer: "Hãng Sản Xuất",
  //type: "Loại",
  //model: "Model",
  shortDescription: "Mô Tả Ngắn",
  price: "Giá",
  stockQty: "Số Lượng Tồn",
  warrantyMonths: "Bảo Hành (Tháng)",
  cpu: "CPU",
  ram: "RAM",
  storage: "Ổ Cứng",
  display: "Màn hình",
  gpu: "GPU",
  os: "Hệ Điều Hành",
  keyboard: "Bàn Phím",
  fingerprintReader: "Vân Tay",
  battery: "Pin",
  camera: "Camera",
  ports: "Cổng Kết Nối",
  wireless: "Kết Nối Không Dây",
  dimensions: "Kích Thước",
  weight: "Trọng Lượng",
  color: "Màu Sắc",
  material: "Chất Liệu",
  condition: "Tình Trạng",
  manufactureYear: "Năm Sản Xuất",
  productId: "Sản Phẩm",
  isPrimary: "Ảnh Chính",
  file: "Ảnh",
  categoryName: "Tên Danh Mục",
  parentCategory: "Danh Mục Cha",
  manufacturerName: "Tên Hãng Sản Xuất",
  warrantyInfo: "Thông Tin Bảo Hành",
  brand: "Thương Hiệu",
  productType: "Loại Sản Phẩm",
  origin: "Xuất Xứ",
  imageUrls: "Ảnh Sản Phẩm",
  parentName: "Danh Mục Cha",
  discountType: "Loại giảm giá",
  discountValue: "Giá trị giảm",
  startDate: "Ngày bắt đầu",
  endDate: "Ngày kết thúc",
  targetNames: "Áp dụng cho",
  quantity: "Số lượng",
  code: "Mã Giảm Giá",
  discount: "Giá Trị Giảm",
  isPercent: "Giảm Theo %",
  usedCount: "Số Lượng Đã Dùng",
  fee: "Chi phí",
};

export default columnLabels;
